server:
  port: 8097

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.tsm.shardingjdbctest.domain

#sharding-jdbc settings
sharding:
  jdbc:
#    datasource:
#      names: mydb_ms0,mydb_ms0_slave0,mydb_ms0_slave1,mydb_ms1,mydb_ms1_slave0,mydb_ms1_slave1
    data-sources:
      mydb_ms0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://ip1:3306/mydb_ms?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      mydb_ms0_slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://ip1:3306/mydb1?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      mydb_ms0_slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://ip1:3306/mydb2?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      mydb_ms1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://ip2:3306/mydb_ms?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      mydb_ms1_slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://ip2:3306/mydb1?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
      mydb_ms1_slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://ip2:3306/mydb2?characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
    master-slave-rule:
      ds_ms0:
        master-data-source-name: mydb_ms0
        slave-data-source-names: [mydb_ms0_slave0,mydb_ms0_slave0]
        load-balance-algorithm-type: round_robin
      ds_ms1:
        master-data-source-name: mydb_ms1
        slave-data-source-names: [mydb_ms1_slave0,mydb_ms1_slave1]
        load-balance-algorithm-type: round_robin
    sharding-rule:
      tables:
        user:
          actual-data-nodes: ds_ms${0..1}.user${1..3}
          database-strategy:
            inline:
              sharding-column: age
              algorithm-inline-expression: ds_ms${age % 2}
          table-strategy:
            inline:
              sharding-column: age
              algorithm-inline-expression: user${age % 3+1}
        age:
          actual-data-nodes: ds_ms${0..1}.age${1..2}
          database-strategy:
            inline:
              sharding-column: id
              algorithm-inline-expression: ds_ms${id % 2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-inline-expression: age${id % 2+1}
#      defaultDataSourceName: ds_0
#      defaultDatabaseStrategy:
#        inline:
#          algorithmExpression: ds_$->{user_id % 2}
#          shardingColumn: user_id

